env:
    browser: true
    es2021: true
extends:
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
    - prettier
overrides: []
parserOptions:
    project: ['./tsconfig.json']
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
rules:
    indent: ['error', 4]